### ISSUE TITLE
Fedora dependencies for HTTPolice

### ISSUE THREAD

**Issue by shinderohitt** [vfaronov/httpolice#2]
You have documented the dependencies for Debian/Ubuntu in the [install docs](https://github.com/vfaronov/httpolice/blob/master/doc/install.rst)

It would be better if you add a row for Fedora users as well. I did a install on `Fedora 24`, and had to install the following packages:

`python-devel redhat-rpm-config libxml2-devel libxslt-devel`

These can be installed on `24` using
`$ dnf install python-devel redhat-rpm-config libxml2-devel libxslt-devel`

**Comment by vfaronov** [comment]
This is now fixed in the [latest docs](http://httpolice.readthedocs.io/en/latest/install.html). It will propagate to the [stable docs](http://httpolice.readthedocs.io/en/stable/install.html) with the next release.
