### ISSUE TITLE
setup.py: Pin lxml version to 3.6.0

### ISSUE THREAD

**Issue by satwikkansal** [vfaronov/httpolice#5]
Hey, our project [coala-quickstart](https://github.com/coala/coala-quickstart) uses HTTpolice as a dependency.

The recent version of lxml (3.8.0) uses `.tar.gz` instead of `wheel`, which is causing builds to fail on 64-bit Windows architecture. It'd be great if the `lxml` version in `setup.py` could be pinned to `3.6.0` which is the last known version by us that used to work.

Build links which are failing: https://ci.appveyor.com/project/coala/coala-quickstart/build/1.0.132/job/rttmk9vcdsq9rl3b 
https://ci.appveyor.com/project/coala/coala-quickstart/build/1.0.134/job/e7jbpvs4jcxko07c

**Comment by vfaronov** [comment]
Hi Satwik, thanks for reaching out. I don’t think this is right, though.

HTTPolice is supposed to be usable as a library, so it cannot afford to pin dependencies like this. Any pinning should be done in a leaf package.

lxml 3.8.0 has many built distributions, including
* [`lxml-3.8.0-cp34-none-win32.whl`](https://pypi.python.org/packages/12/47/83d4f73f1606cafd3bf9f9ba0d6aa630a6eb1df562a060b58e566fd01f3e/lxml-3.8.0-cp34-none-win32.whl#md5=6bc4f9e0fe031757b89ebeaea577e3ad)
* [`lxml-3.8.0-cp35-cp35m-win_amd64.whl`](https://pypi.python.org/packages/5a/5c/4ad3a22c558279188f1e76585a6b130afc9d0f76c7cd6f0134d3c9974d82/lxml-3.8.0-cp35-cp35m-win_amd64.whl#md5=556def2649f4b18551e8fd83c7c35fb3)
* [`lxml-3.8.0.win-amd64-py3.4.exe`](https://pypi.python.org/packages/b9/9b/8736b6a59d2282baab55686d3faa7f6ac3ce1aeff4524e35c0197ec9b505/lxml-3.8.0.win-amd64-py3.4.exe#md5=07b44a961d885ea00d532288d83114fe).

It’s just `lxml-3.8.0-cp34-cp34m-win_amd64.whl` that is missing for some reason.

I suggest you raise this issue with lxml, and if they don’t provide a solution, then pin `lxml==3.6.0` in your own requirements, or simply exclude this particular configuration (Python 3.4 on Windows 64-bit) from your builds.
